spring.application.name=mock interview
# PostgreSQL Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/mockinterviewdb
spring.datasource.username=postgres
spring.datasource.password=Narzo60@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail config (optional)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pawarriteek78@gmail.com
spring.mail.password=Narzo60Pro@1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server port
server.port=8080